### ISSUE TITLE
false positive on a TIFF file

### ISSUE THREAD

**Issue by dvikan** [devttys0/binwalk#100]
https://dvikan.no/files/bridge.png

**Comment by devttys0** [comment]
JPEG Exif headers contain a "structure based closely on TIFF" (http://en.wikipedia.org/wiki/JPEG). In fact, it appears to be exactly like a TIFF header. So the TIFF result isn't a false positive per se; there is in fact a valid TIFF header in the JPEG file.

However, there was a bug in binwalk's JPEG signature that was causing a false negative; this has been fixed and checked into the master code branch:

```
$ binwalk bridge.png 

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
0             0x0             JPEG image data, EXIF standard
12            0xC             TIFF image data, little-endian offset of first image directory: 8
```
Thanks!
