### ISSUE TITLE
Entropy functionality by default depends on pyqtgraph

### ISSUE THREAD

**Issue by marksteward** [devttys0/binwalk#103]
So checking for pyqtgraph before parsing the file will save some wasted time.

**Comment by devttys0** [comment]
Binwalk only attempts to load pyqtgraph if it is trying to generate a visual graph. This way, even if you can't, or don't want to, install pyqtgraph, you can still get useful textual information from binwalk's output regarding file entropy.

Specifying `--nplot` explicitly tells binwalk not to do the graphing, so this will suppress any loading errors.

**Comment by marksteward** [comment]
Yep, but it would be nice for it to fail to load pyqtgraph (if it's going to) before parsing the file. Then someone can explicitly pass --nplot the first time round instead of the second. Admittedly only a small thing, but also only a small change.

Happy to send a PR tomorrow - I've raised this ticket only because I wanted something to refer back to.

**Comment by devttys0** [comment]
Added explicit check for `pyqtgraph` at the beginning of entropy scans. Prints a warning and assumes `--nplot` if the `pyqtgraph` import fails.
