### ISSUE TITLE
TRX Signature Issue

### ISSUE THREAD

**Issue by bmaia** [devttys0/binwalk#105]
Hey Craig, the latest binwalk is not displaying TRX signatures properly, there seems to be some issue with the signature validation.

If I force it to show invalid results (-I), it will display the TRX header with the proper values (the partition offsets seems to be right).

Older commits like 9676166251a72538826ddf09f1f5ccb8839de553 seems to be fine. 

bernardomr@splinter ~/binwalk-latest/src $ ./scripts/binwalk ~/openwrt/openwrt-wrtsl54gs-squashfs.bin

DECIMAL       HEXADECIMAL     DESCRIPTION
^[[A60            0x3C            gzip compressed data, maximum compression, from Unix, NULL date:
2296          0x8F8           LZMA compressed data, properties: 0x6D, dictionary size: 8388608 bytes, uncompressed size: -1 bytes
517152        0x7E420         Squashfs filesystem, little endian, version 2.1, size: 805671 bytes, 269 inodes, blocksize: 65536 bytes, created: 2014-10-29 18:53:25

bernardomr@splinter ~/binwalk-latest/src $ ./scripts/binwalk ~/openwrt/openwrt-wrtsl54gs-squashfs.bin -I

DECIMAL       HEXADECIMAL     DESCRIPTION
32            0x20            TRX firmware header, little endian, header size: 32 bytes, image size: 1323008 bytes, CRC32: 0x6CAC483 flags: 0x0, version: 1, kernel offset: 0x1C, rootfs offset: 0x8D8
60            0x3C            gzip compressed data, maximum compression, from Unix, NULL date:
883           0x373           ARJ archive data, header size: -26758, version 96, minimum version to extract: -45, backup, , original name: "�B��1.Gr3P[�^b|��	cK8����\�e�\�A��U��VH�P[�~", original file date: 1946-12-20 22:58:25, compressed file size: 274714924, uncompressed file size: -2040347968,
2296          0x8F8           LZMA compressed data, properties: 0x6D, dictionary size: 8388608 bytes, uncompressed size: -1 bytes
3116          0xC2C           Microsoft executable,
4011          0xFAB           JFFS2 filesystem, big endian

bernardomr@splinter ~/openwrt $ older-binwalk openwrt-wrtsl54gs-squashfs.bin 

DECIMAL       HEXADECIMAL     DESCRIPTION
32            0x20            TRX firmware header, little endian, header size: 28 bytes, image size: 1323008 bytes, CRC32: 0x6CAC483 flags: 0x0, version: 1
60            0x3C            gzip compressed data, maximum compression, from Unix, NULL date: Wed Dec 31 21:00:00 1969
2296          0x8F8           LZMA compressed data, properties: 0x6D, dictionary size: 8388608 bytes, uncompressed size: -1 bytes
517152        0x7E420         Squashfs filesystem, little endian, version 2.1, size: 805671 bytes,  269 inodes, blocksize: 65536 bytes, created: Wed Oct 29 16:53:25 2014

bernardomr@splinter ~/openwrt $ hexdump -C openwrt-wrtsl54gs-squashfs.bin | head
00000000  57 35 34 55 00 00 00 00  07 02 03 02 08 01 55 32  |W54U..........U2|
00000010  4e 44 00 00 1f 00 00 00  00 00 00 00 00 00 00 00  |ND..............|
00000020  48 44 52 30 00 30 14 00  83 c4 ca 06 00 00 01 00  |HDR0.0..........|
00000030  1c 00 00 00 d8 08 00 00  00 e4 07 00 1f 8b 08 00  |................|
00000040  00 00 00 00 02 03 a5 56  41 6c 1b 69 15 fe fc cf  |.......VAl.i....|
00000050  24 71 d2 b8 4c 1c b7 9a  96 aa 9a bf 9e 38 56 b3  |$q..L........8V.|
00000060  a0 59 d6 2a 59 c9 12 83  ed ae 72 e8 21 a4 3d f4  |.Y.*Y.....r.!.=.|
00000070  b0 5a 99 34 82 1e 16 29  5a 90 e8 81 c3 28 ed 4a  |.Z.4...)Z....(.J|
00000080  01 bc 1d 03 5d 61 c4 c5  4a 9c 6e 0f 69 6c 76 59  |....]a..J.n.ilvY|
00000090  d8 c3 b6 8d 92 15 db 43  81 15 5c 38 21 ab ad a0  |.......C..\8!...|

**Comment by devttys0** [comment]
Latest commit should fix this, thanks!
