### ISSUE TITLE
Binwalk halts on encrypted .zip

### ISSUE THREAD

**Issue by sviehb** [devttys0/binwalk#108]
Commit https://github.com/devttys0/binwalk/commit/a048aca485dfd4aad187fd8b0776d6fe8265989f causes binwalk to halt when an encrypted .zip is encountered.
`7z` interactively asks for the .zip password. Passing a blank password like so `^zip archive data:zip:7z x -y '%e' -p '':0,1` avoids the password prompt.
Note: 7z writes empty files (plus directory structure) for files which could not be decrypted.

**Comment by devttys0** [comment]
Fixed, thanks!
