### ISSUE TITLE
Custom signature format

### ISSUE THREAD

**Issue by bmaia** [devttys0/binwalk#112]
Quick question: Is it possible to create a custom signature with multiple magic headers? I have found some custom uImage file headers, like this one from NETGEAR:

https://github.com/cidermole/wndr3800-uboot/blob/2a3c20a515bdcfad28f75469784973e8921dcbab/include/image.h#L136-L153

I didn't manage to find an easy way to create a conditional statement for this (based on the libmagic file format). I tried things like this but they didn't work (and it seems to have a poor performance):

0		byte		>0
\>0      belong    0x27051956     uImage header, header size: 64 bytes,
\>0      belong    0x33373031     uImage header, header size: 64 bytes,
(...)

The best way to add this custom signature seems to be creating multiple entries, do you have any better idea?

0      belong    0x27051956     uImage header, header size: 64 bytes,
\>4     ubelong   x              header CRC: 0x%X,
\>8     bedate    x              created: %s,
\>12    belong    <1             {invalid}
(...)

0      belong    0x33373031     uImage header, header size: 64 bytes,
\>4     ubelong   x              header CRC: 0x%X,
\>8     bedate    x              created: %s,
\>12    belong    <1             {invalid}
(...)

**Comment by devttys0** [comment]
You should be able to do this with regex:

```
0    regex    (\x27\x05\x19\x56|\x33\x37\x30\x31)    uImage header, header size: 64 bytes,
...
```
