### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by pisto** [devttys0/binwalk#140]
[This file](https://www.pisto.horse/R84HF_DANT-P-AA.bli) causes an endless loop in tinfl_decompress() from libminiz.so. Before getting stuck it prints:
```
8291564       0x7E84EC        SEAMA firmware header, little endian, meta size: 65039, size: 1375325160
```
My miniz version is 1.15.

**Comment by devttys0** [comment]
The tinfl library is no longer used by binwalk. Using the latest version of binwalk from the git master branch should fix this issue.
