### ISSUE TITLE
how can I solve these problems !?

### ISSUE THREAD

**Issue by rasadeyan** [devttys0/binwalk#141]
WARNING: Failed to load plugin module 'zlibvalid': Failed to locate libraries '['tinfl']'

WARNING: Failed to load plugin module 'compressd': Failed to locate libraries '['compress42']'

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate libraries '['tinfl']'

WARNING: Failed to load plugin module 'compressd': Failed to locate libraries '['compress42']'

**Comment by devttys0** [comment]
Those libraries are no longer in use by binwalk. Using the latest code from the master branch should fix these issues.
