### ISSUE TITLE
Failed to Load Plugin Module in MacOS 10.10.5

### ISSUE THREAD

**Issue by bl4ckic3** [devttys0/binwalk#150]
I have problem with binwalk. 
Everytime I run it, I get an error for :
 binwalk firmware.mg 

WARNING: Failed to load plugin module 'compressd': Failed to locate libraries '['compress42']'

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate libraries '['tinfl']'

WARNING: Failed to load plugin module 'compressd': Failed to locate libraries '['compress42']'

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate libraries '['tinfl']'

Where I can add this libraries, previous issues solutions referring to copy dylib files which does not exist in the current version of binwalk.

**Comment by niklaus520** [comment]
https://github.com/devttys0/binwalk/issues/77#issuecomment-77284013

just google it

**Comment by bl4ckic3** [comment]
As I already mentioned I already did that.
 I manually installed binwalk: Result was the same. 
I tried to copy those files mentioned in the other issues  (e.g. copying *.dylib files to /usr/local/lib/ or 
 src/C/compress/libcompress42.dylib to /usr/local/lib/) but as I mentioned earlier such files does not exist in the Binwalk anymore.

**Comment by niklaus520** [comment]
Have u tried compile the source code first? Cause i just download the source code, configure, make, make install then copy, all worked fine

**Comment by bl4ckic3** [comment]
I downloaded the source from github. Here is the output from source installation (did it again right now) 

Majids-Air:binwalk-master majid$ sudo python setup.py install
Password:
running install
running build
running build_py
running build_scripts
running install_lib
copying build/lib/binwalk/__init__.py -> /usr/local/lib/python2.7/site-packages/binwalk
copying build/lib/binwalk/config/extract.conf -> /usr/local/lib/python2.7/site-packages/binwalk/config
copying build/lib/binwalk/core/__init__.py -> /usr/local/lib/python2.7/site-packages/binwalk/core
copying build/lib/binwalk/core/C.py -> /usr/local/lib/python2.7/site-packages/binwalk/core
copying build/lib/binwalk/core/common.py -> /usr/local/lib/python2.7/site-packages/binwalk/core
copying build/lib/binwalk/core/compat.py -> /usr/local/lib/python2.7/site-packages/binwalk/core
copying build/lib/binwalk/core/display.py -> /usr/local/lib/python2.7/site-packages/binwalk/core
copying build/lib/binwalk/core/idb.py -> /usr/local/lib/python2.7/site-packages/binwalk/core
copying build/lib/binwalk/core/magic.py -> /usr/local/lib/python2.7/site-packages/binwalk/core
copying build/lib/binwalk/core/module.py -> /usr/local/lib/python2.7/site-packages/binwalk/core
copying build/lib/binwalk/core/plugin.py -> /usr/local/lib/python2.7/site-packages/binwalk/core
copying build/lib/binwalk/core/settings.py -> /usr/local/lib/python2.7/site-packages/binwalk/core
copying build/lib/binwalk/magic/archives -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/binarch -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/bincast -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/binwalk -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/bootloaders -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/code -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/compressed -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/console -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/crypto -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/ecos -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/encoding -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/executables -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/filesystems -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/firmware -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/hashing -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/images -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/linux -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/lzma -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/misc -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/network -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/sql -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/magic/vxworks -> /usr/local/lib/python2.7/site-packages/binwalk/magic
copying build/lib/binwalk/modules/__init__.py -> /usr/local/lib/python2.7/site-packages/binwalk/modules
copying build/lib/binwalk/modules/binvis.py -> /usr/local/lib/python2.7/site-packages/binwalk/modules
copying build/lib/binwalk/modules/compression.py -> /usr/local/lib/python2.7/site-packages/binwalk/modules
copying build/lib/binwalk/modules/disasm.py -> /usr/local/lib/python2.7/site-packages/binwalk/modules
copying build/lib/binwalk/modules/entropy.py -> /usr/local/lib/python2.7/site-packages/binwalk/modules
copying build/lib/binwalk/modules/extractor.py -> /usr/local/lib/python2.7/site-packages/binwalk/modules
copying build/lib/binwalk/modules/general.py -> /usr/local/lib/python2.7/site-packages/binwalk/modules
copying build/lib/binwalk/modules/hashmatch.py -> /usr/local/lib/python2.7/site-packages/binwalk/modules
copying build/lib/binwalk/modules/heuristics.py -> /usr/local/lib/python2.7/site-packages/binwalk/modules
copying build/lib/binwalk/modules/hexdiff.py -> /usr/local/lib/python2.7/site-packages/binwalk/modules
copying build/lib/binwalk/modules/signature.py -> /usr/local/lib/python2.7/site-packages/binwalk/modules
copying build/lib/binwalk/plugins/arcadyan.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
copying build/lib/binwalk/plugins/compressd.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
copying build/lib/binwalk/plugins/cpio.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
copying build/lib/binwalk/plugins/gzipextract.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
copying build/lib/binwalk/plugins/gzipvalid.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
copying build/lib/binwalk/plugins/jffs2valid.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
copying build/lib/binwalk/plugins/lzmaextract.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
copying build/lib/binwalk/plugins/lzmamod.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
copying build/lib/binwalk/plugins/lzmavalid.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
copying build/lib/binwalk/plugins/tar.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
copying build/lib/binwalk/plugins/unjffs2.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
copying build/lib/binwalk/plugins/ziphelper.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
copying build/lib/binwalk/plugins/zlibextract.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
copying build/lib/binwalk/plugins/zlibvalid.py -> /usr/local/lib/python2.7/site-packages/binwalk/plugins
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/core/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/core/C.py to C.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/core/common.py to common.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/core/compat.py to compat.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/core/display.py to display.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/core/idb.py to idb.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/core/magic.py to magic.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/core/module.py to module.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/core/plugin.py to plugin.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/core/settings.py to settings.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/modules/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/modules/binvis.py to binvis.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/modules/compression.py to compression.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/modules/disasm.py to disasm.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/modules/entropy.py to entropy.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/modules/extractor.py to extractor.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/modules/general.py to general.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/modules/hashmatch.py to hashmatch.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/modules/heuristics.py to heuristics.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/modules/hexdiff.py to hexdiff.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/modules/signature.py to signature.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/arcadyan.py to arcadyan.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/compressd.py to compressd.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/cpio.py to cpio.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/gzipextract.py to gzipextract.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/gzipvalid.py to gzipvalid.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/jffs2valid.py to jffs2valid.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/lzmaextract.py to lzmaextract.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/lzmamod.py to lzmamod.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/lzmavalid.py to lzmavalid.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/tar.py to tar.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/unjffs2.py to unjffs2.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/ziphelper.py to ziphelper.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/zlibextract.py to zlibextract.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/binwalk/plugins/zlibvalid.py to zlibvalid.pyc
running install_scripts
copying build/scripts-2.7/binwalk -> /usr/local/bin
changing mode of /usr/local/bin/binwalk to 755
running install_egg_info
Removing /usr/local/lib/python2.7/site-packages/binwalk-2.1.0-py2.7.egg-info
Writing /usr/local/lib/python2.7/site-packages/binwalk-2.1.0-py2.7.egg-info
Majids-Air:binwalk-master majid$ 

And then I run binwalk:

Alis-Air:Firmware ali$ binwalk swu8x_mr_1.5.8_20121212.bin 

WARNING: Failed to load plugin module 'compressd': Failed to locate libraries '['compress42']'

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate libraries '['tinfl']'

WARNING: Failed to load plugin module 'compressd': Failed to locate libraries '['compress42']'

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate libraries '['tinfl']'

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
98944         0x18280         U-Boot version string, "U-Boot 1.1.3 (Jun 29 2012 - 13:43:39)"
118246        0x1CDE6         Zlib compressed data, compressed
118307        0x1CE23         Zlib compressed data, compressed
266240        0x41000         uImage header, header size: 64 bytes, header CRC: 0x82242F46, created: Wed Dec 12 09:07:57 2012, image size: 6027892 bytes, Data Address: 0x80000000, Entry Point: 0x8035F000, data CRC: 0x5AB5EA67, OS: Linux, CPU: MIPS, image type: OS Kernel Image, compression type: lzma, image name: "Linux Kernel Image"
266304        0x41040         LZMA compressed data, properties: 0x5D, dictionary size: 33554432 bytes, uncompressed size: 8495822 bytes
274723        0x43123         Zlib compressed data, compressed
278976        0x441C0         Zlib compressed data, best compression
316810        0x4D58A         Zlib compressed data, default compression
370708        0x5A814         Zlib compressed data, best compression
380113        0x5CCD1         Zlib compressed data, compressed
405030        0x62E26         Zlib compressed data, default compression
408535        0x63BD7         Zlib compressed data, default compression
..............

**Comment by niklaus520** [comment]
The python installer failed to compile the lib, so just do:

```
./configure
make
sudo make install
sudo cp src/C/miniz/libtinfl.dylib /usr/local/lib/
sudo cp src/C/compress/libcompress42.dylib /usr/local/lib/
```

BTW, i suppose you haven't read all the comments in the page that i mentioned.

**Comment by bl4ckic3** [comment]
I particularly mentioned what you quoted right now in my answer. Did you see my comment? 
Would you please tell me where do you find this libcompress42.dylib in the binwalk installation folder that I do not?

**Comment by niklaus520** [comment]
![image](https://cloud.githubusercontent.com/assets/3125626/9428101/c979fba6-49d0-11e5-9d13-07da01f18f00.png)

**Comment by bl4ckic3** [comment]
Which version of binwalk you are using. I do not find libs folder even in the current version of binwalk : 
https://github.com/devttys0/binwalk/tree/master/src/binwalk
![screen shot 2015-08-23 at 1 56 19 pm](https://cloud.githubusercontent.com/assets/5967919/9428114/f143b44c-499e-11e5-804f-e4b456db2c49.png)

**Comment by niklaus520** [comment]
https://github.com/devttys0/binwalk/releases/tag/v2.0.1 

The release 2.0.1 version, i think it's the stable version

**Comment by niklaus520** [comment]
I just clone the newest version code, i think they just removed configure file

**Comment by bl4ckic3** [comment]
Fixed. Thanks. I forked it from github. In github source there were no lib and C folders.

**Comment by devttys0** [comment]
Yes, the latest code in github has removed the C libraries, so this should no longer be a problem. A new stable release is probably overdue at this point. :) Thanks niklaus520!
