### ISSUE TITLE
Zlib False positive

### ISSUE THREAD

**Issue by amabm** [devttys0/binwalk#155]
when i try to analyze this using binwalk it gives me huge amount of Zlib compressed data
and sure can't be uncompressed
it is STB firmware...can this be fixed?
http://www.mediafire.com/download/h825beatzpb0x68/MST999_H3_V1.67_17-06-2014.rar
thanks :smile:

**Comment by devttys0** [comment]
I don't have experience with this specific firmware, but for me all of the Zlib entries were decompressed, and at least some of them are definitively valid (e.g., one of them is a JPEG image of a satellite). Can you provide more specific details on which Zlib offsets you weren't able to decompress?
