### ISSUE TITLE
Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

### ISSUE THREAD

**Issue by iddq** [devttys0/binwalk#157]
root@debian:/usr/src/binwalk# python3 setup.py uninstall
running uninstall
removing '/usr/local/lib/python3.4/dist-packages/binwalk' (and everything under it)
removing 'b'/usr/local/bin/binwalk''
root@debian:/usr/src/binwalk# rm -rf /root/.binwalk/
root@debian:/usr/src# git clone https://github.com/devttys0/binwalk.git
Cloning into 'binwalk'...
remote: Counting objects: 5894, done.
remote: Total 5894 (delta 0), reused 0 (delta 0), pack-reused 5894
Receiving objects: 100% (5894/5894), 6.64 MiB | 474.00 KiB/s, done.
Resolving deltas: 100% (3379/3379), done.
Checking connectivity... done.
root@debian:/usr/src/binwalk# python3 setup.py install
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/binwalk
copying binwalk/__init__.py -> build/lib/binwalk
creating build/lib/binwalk/magic
copying binwalk/magic/firmware -> build/lib/binwalk/magic
copying binwalk/magic/bootloaders -> build/lib/binwalk/magic
copying binwalk/magic/binwalk -> build/lib/binwalk/magic
copying binwalk/magic/ecos -> build/lib/binwalk/magic
copying binwalk/magic/crypto -> build/lib/binwalk/magic
copying binwalk/magic/bincast -> build/lib/binwalk/magic
copying binwalk/magic/executables -> build/lib/binwalk/magic
copying binwalk/magic/vxworks -> build/lib/binwalk/magic
copying binwalk/magic/lzma -> build/lib/binwalk/magic
copying binwalk/magic/encoding -> build/lib/binwalk/magic
copying binwalk/magic/console -> build/lib/binwalk/magic
copying binwalk/magic/filesystems -> build/lib/binwalk/magic
copying binwalk/magic/code -> build/lib/binwalk/magic
copying binwalk/magic/sql -> build/lib/binwalk/magic
copying binwalk/magic/network -> build/lib/binwalk/magic
copying binwalk/magic/misc -> build/lib/binwalk/magic
copying binwalk/magic/linux -> build/lib/binwalk/magic
copying binwalk/magic/hashing -> build/lib/binwalk/magic
copying binwalk/magic/binarch -> build/lib/binwalk/magic
copying binwalk/magic/images -> build/lib/binwalk/magic
copying binwalk/magic/compressed -> build/lib/binwalk/magic
copying binwalk/magic/archives -> build/lib/binwalk/magic
creating build/lib/binwalk/config
copying binwalk/config/extract.conf -> build/lib/binwalk/config
creating build/lib/binwalk/plugins
copying binwalk/plugins/ziphelper.py -> build/lib/binwalk/plugins
copying binwalk/plugins/zlibextract.py -> build/lib/binwalk/plugins
copying binwalk/plugins/zlibvalid.py -> build/lib/binwalk/plugins
copying binwalk/plugins/lzmaextract.py -> build/lib/binwalk/plugins
copying binwalk/plugins/gzipextract.py -> build/lib/binwalk/plugins
copying binwalk/plugins/gzipvalid.py -> build/lib/binwalk/plugins
copying binwalk/plugins/arcadyan.py -> build/lib/binwalk/plugins
copying binwalk/plugins/unjffs2.py -> build/lib/binwalk/plugins
copying binwalk/plugins/compressd.py -> build/lib/binwalk/plugins
copying binwalk/plugins/lzmavalid.py -> build/lib/binwalk/plugins
copying binwalk/plugins/lzmamod.py -> build/lib/binwalk/plugins
copying binwalk/plugins/ubivalid.py -> build/lib/binwalk/plugins
copying binwalk/plugins/jffs2valid.py -> build/lib/binwalk/plugins
copying binwalk/plugins/tar.py -> build/lib/binwalk/plugins
copying binwalk/plugins/cpio.py -> build/lib/binwalk/plugins
creating build/lib/binwalk/modules
copying binwalk/modules/disasm.py -> build/lib/binwalk/modules
copying binwalk/modules/hexdiff.py -> build/lib/binwalk/modules
copying binwalk/modules/entropy.py -> build/lib/binwalk/modules
copying binwalk/modules/heuristics.py -> build/lib/binwalk/modules
copying binwalk/modules/binvis.py -> build/lib/binwalk/modules
copying binwalk/modules/compression.py -> build/lib/binwalk/modules
copying binwalk/modules/extractor.py -> build/lib/binwalk/modules
copying binwalk/modules/general.py -> build/lib/binwalk/modules
copying binwalk/modules/hashmatch.py -> build/lib/binwalk/modules
copying binwalk/modules/__init__.py -> build/lib/binwalk/modules
copying binwalk/modules/signature.py -> build/lib/binwalk/modules
creating build/lib/binwalk/core
copying binwalk/core/idb.py -> build/lib/binwalk/core
copying binwalk/core/common.py -> build/lib/binwalk/core
copying binwalk/core/compat.py -> build/lib/binwalk/core
copying binwalk/core/plugin.py -> build/lib/binwalk/core
copying binwalk/core/display.py -> build/lib/binwalk/core
copying binwalk/core/C.py -> build/lib/binwalk/core
copying binwalk/core/module.py -> build/lib/binwalk/core
copying binwalk/core/settings.py -> build/lib/binwalk/core
copying binwalk/core/magic.py -> build/lib/binwalk/core
copying binwalk/core/__init__.py -> build/lib/binwalk/core
running build_scripts
creating build/scripts-3.4
copying and adjusting scripts/binwalk -> build/scripts-3.4
changing mode of build/scripts-3.4/binwalk from 644 to 755
running install_lib
creating /usr/local/lib/python3.4/dist-packages/binwalk
creating /usr/local/lib/python3.4/dist-packages/binwalk/modules
copying build/lib/binwalk/modules/disasm.py -> /usr/local/lib/python3.4/dist-packages/binwalk/modules
copying build/lib/binwalk/modules/hexdiff.py -> /usr/local/lib/python3.4/dist-packages/binwalk/modules
copying build/lib/binwalk/modules/entropy.py -> /usr/local/lib/python3.4/dist-packages/binwalk/modules
copying build/lib/binwalk/modules/heuristics.py -> /usr/local/lib/python3.4/dist-packages/binwalk/modules
copying build/lib/binwalk/modules/binvis.py -> /usr/local/lib/python3.4/dist-packages/binwalk/modules
copying build/lib/binwalk/modules/compression.py -> /usr/local/lib/python3.4/dist-packages/binwalk/modules
copying build/lib/binwalk/modules/extractor.py -> /usr/local/lib/python3.4/dist-packages/binwalk/modules
copying build/lib/binwalk/modules/general.py -> /usr/local/lib/python3.4/dist-packages/binwalk/modules
copying build/lib/binwalk/modules/hashmatch.py -> /usr/local/lib/python3.4/dist-packages/binwalk/modules
copying build/lib/binwalk/modules/__init__.py -> /usr/local/lib/python3.4/dist-packages/binwalk/modules
copying build/lib/binwalk/modules/signature.py -> /usr/local/lib/python3.4/dist-packages/binwalk/modules
creating /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/ziphelper.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/zlibextract.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/zlibvalid.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/lzmaextract.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/gzipextract.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/gzipvalid.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/arcadyan.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/unjffs2.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/compressd.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/lzmavalid.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/lzmamod.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/ubivalid.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/jffs2valid.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/tar.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
copying build/lib/binwalk/plugins/cpio.py -> /usr/local/lib/python3.4/dist-packages/binwalk/plugins
creating /usr/local/lib/python3.4/dist-packages/binwalk/core
copying build/lib/binwalk/core/idb.py -> /usr/local/lib/python3.4/dist-packages/binwalk/core
copying build/lib/binwalk/core/common.py -> /usr/local/lib/python3.4/dist-packages/binwalk/core
copying build/lib/binwalk/core/compat.py -> /usr/local/lib/python3.4/dist-packages/binwalk/core
copying build/lib/binwalk/core/plugin.py -> /usr/local/lib/python3.4/dist-packages/binwalk/core
copying build/lib/binwalk/core/display.py -> /usr/local/lib/python3.4/dist-packages/binwalk/core
copying build/lib/binwalk/core/C.py -> /usr/local/lib/python3.4/dist-packages/binwalk/core
copying build/lib/binwalk/core/module.py -> /usr/local/lib/python3.4/dist-packages/binwalk/core
copying build/lib/binwalk/core/settings.py -> /usr/local/lib/python3.4/dist-packages/binwalk/core
copying build/lib/binwalk/core/magic.py -> /usr/local/lib/python3.4/dist-packages/binwalk/core
copying build/lib/binwalk/core/__init__.py -> /usr/local/lib/python3.4/dist-packages/binwalk/core
copying build/lib/binwalk/__init__.py -> /usr/local/lib/python3.4/dist-packages/binwalk
creating /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/firmware -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/bootloaders -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/binwalk -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/ecos -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/crypto -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/bincast -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/executables -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/vxworks -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/lzma -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/encoding -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/console -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/filesystems -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/code -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/sql -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/network -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/misc -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/linux -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/hashing -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/binarch -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/images -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/compressed -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
copying build/lib/binwalk/magic/archives -> /usr/local/lib/python3.4/dist-packages/binwalk/magic
creating /usr/local/lib/python3.4/dist-packages/binwalk/config
copying build/lib/binwalk/config/extract.conf -> /usr/local/lib/python3.4/dist-packages/binwalk/config
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/modules/disasm.py to disasm.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/modules/hexdiff.py to hexdiff.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/modules/entropy.py to entropy.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/modules/heuristics.py to heuristics.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/modules/binvis.py to binvis.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/modules/compression.py to compression.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/modules/extractor.py to extractor.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/modules/general.py to general.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/modules/hashmatch.py to hashmatch.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/modules/__init__.py to __init__.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/modules/signature.py to signature.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/ziphelper.py to ziphelper.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/zlibextract.py to zlibextract.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/zlibvalid.py to zlibvalid.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/lzmaextract.py to lzmaextract.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/gzipextract.py to gzipextract.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/gzipvalid.py to gzipvalid.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/arcadyan.py to arcadyan.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/unjffs2.py to unjffs2.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/compressd.py to compressd.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/lzmavalid.py to lzmavalid.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/lzmamod.py to lzmamod.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/ubivalid.py to ubivalid.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/jffs2valid.py to jffs2valid.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/tar.py to tar.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/plugins/cpio.py to cpio.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/core/idb.py to idb.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/core/common.py to common.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/core/compat.py to compat.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/core/plugin.py to plugin.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/core/display.py to display.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/core/C.py to C.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/core/module.py to module.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/core/settings.py to settings.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/core/magic.py to magic.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/core/__init__.py to __init__.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/binwalk/__init__.py to __init__.cpython-34.pyc
running install_scripts
copying build/scripts-3.4/binwalk -> /usr/local/bin
changing mode of /usr/local/bin/binwalk to 755
running install_egg_info
Removing /usr/local/lib/python3.4/dist-packages/binwalk-2.1.0.egg-info
Writing /usr/local/lib/python3.4/dist-packages/binwalk-2.1.0.egg-info
root@debian:/usr/src/binwalk# binwalk -v

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly

WARNING: Error loading plugin 'compressd.py': Can't convert 'module' object to str implicitly
root@debian:/usr/src/binwalk#

**Comment by devttys0** [comment]
Just pushed a commit to master that should fix this.
