### ISSUE TITLE
new release version / git tag

### ISSUE THREAD

**Issue by anthraxx** [devttys0/binwalk#160]
Hey, its quite some time... its not really an "issue", but I would like to ask if you could consider to make a new release version.
The current git HEAD feels kind of stable and the last release is really long ago :smile: 

thank you very much for this very useful tool and all the hard work that went into it :+1:

**Comment by devttys0** [comment]
[Merry Christmas](https://github.com/devttys0/binwalk/releases/tag/v2.1.1)!
