### ISSUE TITLE
AttributeError: __exit__ on run

### ISSUE THREAD

**Issue by zbuc** [devttys0/binwalk#169]
Haven't had time to debug this yet.

Cloned repository, "sudo python setup.py install", reported no errors.

However, the Python launcher script seems to have a bug somewhere:

```
~ $ binwalk
Traceback (most recent call last):
  File "/usr/local/bin/binwalk", line 57, in <module>
    main()
  File "/usr/local/bin/binwalk", line 29, in main
    with binwalk.Modules() as modules:
AttributeError: __exit__
```

**Comment by devttys0** [comment]
I'd expect to see this error if the `Modules` class didn't have the `__exit__` method, but [it does](https://github.com/devttys0/binwalk/blob/master/src/binwalk/core/module.py#L254). This was a recent change to the code, so make sure you are fully updated.

As a sanity check, I did a full uninstall and re-install, and could not replicate this issue:

```
$ sudo python setup.py uninstall
$ sudo python setup.py install
```
