### ISSUE TITLE
Failed to run external extractor [HELP]

### ISSUE THREAD

**Issue by Fabio0dev0** [devttys0/binwalk#171]
0             0x0             Ubiquiti firmware header, header size: 264 bytes, ~CRC32: 0x74D4AF1, version: "XM.ar7240.v5.5.12536.120406.1455"
260           0x104           Ubiquiti partition header, header size: 56 bytes, name: "PARTu-boot", base address: 0x00000000, data size: 0 bytes
151156        0x24E74         U-Boot version string, "U-Boot 1.1.4.2-s550 (Feb  9 2012 - 17:16:25)"
152388        0x25344         CRC32 polynomial table, big endian
182596        0x2C944         Ubiquiti partition header, header size: 56 bytes, name: "PARTkernel", base address: 0x00000001, data size: -2147475456 bytes
182660        0x2C984         uImage header, header size: 64 bytes, header CRC: 0x66B66596, created: 2012-04-06 11:56:34, image size: 1047143 bytes, Data Address: 0x80002000, Entry Point: 0x80002000, data CRC: 0xAD222337, OS: Linux, CPU: MIPS, image type: OS Kernel Image, compression type: lzma, image name: "MIPS Ubiquiti Linux-2.6.32.54"
182724        0x2C9C4         LZMA compressed data, properties: 0x5D, dictionary size: 8388608 bytes, uncompressed size: 3037760 bytes
1229867       0x12C42B        Ubiquiti partition header, header size: 56 bytes, name: "PARTrootfs", base address: 0x00000002, data size: 0 bytes

WARNING: Extractor.execute failed to run external extractor 'unsquashfs -d '%%squashfs-root%%' '%e'': [Errno 2] No such file or directory
WARNING: Extractor.execute failed to run external extractor 'sasquatch -p 1 -le -d '%%squashfs-root%%' '%e'': [Errno 2] No such file or directory
WARNING: Extractor.execute failed to run external extractor 'sasquatch -p 1 -be -d '%%squashfs-root%%' '%e'': [Errno 2] No such file or directory

1229931       0x12C46B        Squashfs filesystem, little endian, version 4.0, compression:lzma, size: 4983781 bytes, 1200 inodes, blocksize: 131072 bytes, created: 2012-04-06 11:56:36

**Comment by devttys0** [comment]
The extraction tools `unsquashfs` and `sasquatch` aren't installed on your system. Check out the [installation documentation](https://github.com/devttys0/binwalk/wiki/Quick-Start-Guide) on how to install optional extraction utilities.
