### ISSUE TITLE
zlib plugin problem

### ISSUE THREAD

**Issue by Zarados** [devttys0/binwalk#188]
hey guys, I get some problems.
I can't detect zlib data, but my friends can do it.
I not sure where is the problem happen. Is the python or the binwalk?
My python version is 2.7.9 and binwalk version 2.0.0.
How can i check zlib plugin? 
Thanks.

**Comment by devttys0** [comment]
First, try the latest code from the repository and see if you have the same problems (v2.0.0 is pretty old): https://github.com/devttys0/binwalk/archive/master.zip
