### ISSUE TITLE
Can't seem to extract `LANCOM WWAN firmware` correctly

### ISSUE THREAD

**Issue by VeNoMouS** [devttys0/binwalk#197]
This firmware image is from mobotix security camera http://blog.kislyakoff.ru/firmware/mobotix/4.3.4.83/MX_system_4_3483.mpl 

If I --dd='.*' it seems to extract an 8mb file from the 30mb... but I can't identify the file , binwalk seems to think that extract 8mb is still a `LANCOM WWAN firmware`

**Comment by devttys0** [comment]
Aside from the header (ASCII text), this firmware image appears almost certainly encrypted.

**Comment by VeNoMouS** [comment]
Alright, Cheers @devttys0 i'll try take the unit apart and see if they have a JTAG that I can mess with.
