### ISSUE TITLE
Package

### ISSUE THREAD

**Issue by rfminelli** [devttys0/binwalk#205]
How can we package the firmware after extracted.
Sorry if the question is the wrong place.

**Comment by Lekensteyn** [comment]
I don't think this the goal of binwalk. Using binwalk you can analyze files and execute arbitrary commands based on signature matches. This is a one-way operation, packing it is not possible (and if it were, then it would be possible only in a limited number of cases).

**Comment by devttys0** [comment]
As Lekensteyn said, binwalk doesn't do re-construction of firmware after it has been extracted. Doing so is typically a manual process, although there are some tools that can automate this for limited numbers of firmwares (see: https://bitsum.com/firmware_mod_kit.htm).
