### ISSUE TITLE
ImportError: No module named core.module

### ISSUE THREAD

**Issue by shadyproject** [devttys0/binwalk#210]
Trying to use binwalk in a virtualenv, and I get the following error trying to import binwalk 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/src/sahara/venv/lib/python2.7/site-packages/binwalk/__init__.py", line 3, in <module>
    from binwalk.core.module import Modules, ModuleException
ImportError: No module named core.module
```

This occurs both when the venv is activated via `source venv/bin/activate` or when the venv python is called directly via `venv/bin/python`

Thoughts?

**Comment by devttys0** [comment]
Does the file `/Users/username/src/sahara/venv/lib/python2.7/site-packages/binwalk/core/module.py` exist?

**Comment by blackt3a** [comment]
sudo apt purge binwalk
sudo apt autoclean
sudo apt-get install binwalk
python3 -m pip install git+https://github.com/ReFirmLabs/binwalk
