### ISSUE TITLE
not working for me 

### ISSUE THREAD

**Issue by ralo21** [devttys0/binwalk#220]
i guy , i have to disassemble a firwmare 

this : http://storow.xirodrone.com/attac-UA3500_FCU_FW_1.0.0_20150710.bin

i have installed ubuntu in virtualbox and binwalk 

when i analyze with binwalk i have blank line and when i extract nothing just blank line 

sorry for my english :( 

if you have idea :) 

thank you

**Comment by devttys0** [comment]
There's nothing to extract from this firmware. There does not appear to be any compression, encryption, file systems, etc. It's just straight ARM code - load the .bin file directly into any ARM disassembler.

**Comment by ralo21** [comment]
its crypted :(

**Comment by devttys0** [comment]
I see nothing in the linked firmware image that suggests encryption of any type. There are plain text strings and code. What leads you to believe that it is encrypted?

**Comment by ralo21** [comment]
I can't see the string :( what use for see that ?

Thank you

**Comment by hoover2015** [comment]
Please don't help him. He's breaking the law. 


Zero Tech USA Co., Ltd
Add: 690 N. Berry St. Suite B,
Brea, CA 92821
Tel： (714) 592-7666

**Comment by ralo21** [comment]
You can close , i have found how to thank you guys :)
