### ISSUE TITLE
Fuzzy Hash (hashmatch) not a available

### ISSUE THREAD

**Issue by kfken** [devttys0/binwalk#223]
I cloned the latest repo, ran deps.sh and installed, however when I use -h, none of the fuzzy hashing options are available.  None of the switches are recognized; it appears as if the module is not being loaded.  Is it not currently supported?

**Comment by devttys0** [comment]
Correct, fuzzy hashing is no longer supported in binwalk. There are many other tools that are dedicated to this feature, such as ssdeep.
