### ISSUE TITLE
3D option

### ISSUE THREAD

**Issue by jresch** [devttys0/binwalk#227]
Hello!

I have installed your software after finding this post:
http://binwalk.org/3d-data-visualizations/#comment-47711

However, I couldn't find the -3D option. 
I'd love to use it to visualization some data :)

Thanks 
Janelle

**Comment by jresch** [comment]
Oh hang on, does it only work for python3?

**Comment by jresch** [comment]
Doesn't seem to be working for python3 either

**Comment by devttys0** [comment]
The 3D options are no longer supported by binwalk. Check out binglide, which has better 3D (and other) visualization features: https://github.com/wapiflapi/binglide
