### ISSUE TITLE
Rebuild ?

### ISSUE THREAD

**Issue by afby** [devttys0/binwalk#236]
Thanks for your job !!!

Any chance to have a option to rebuild the firmware after extract and modification ?

**Comment by BenGardiner** [comment]
fmk is a good option for this. see https://github.com/rampageX/firmware-mod-kit

**Comment by devttys0** [comment]
Putting things back together is much harder than taking them apart. :)  FMK is old and no longer maintained, but can be a good starting point if you need to automate re-building your firmware. I don't have any plans to add this functionality to binwalk.

**Comment by afby** [comment]
thanx for reponse ! its a pity!!
