### ISSUE TITLE
decryption tool

### ISSUE THREAD

**Issue by superhache** [devttys0/binwalk#248]
Hello , 
im trying to extract /decrypt a router fimware (Technicolor tg582n)
and i am getting this error

Thompson/Alcatel encoded firmware, version: 10.2.5.2, size: 7558799, crc: 0xB1F09887, try decryption tool from: http://download.modem-help.co.uk/mfcs-A/Alcatel/Modems/Misc/

but that site is down, where i can get that tool ¿
thanks

**Comment by 0BuRner** [comment]
http://chomikuj.pl/Kicek_171/Router+Thomson+TG789vn/Decrypt-Firmware_v1.2,4093385501.7z(archive)

http://chomikuj.pl/AiXsL/Komputer+Programy+Sterowniki+PC/Sterowniki+r*c3*b3*c5*bcne/Router+Thomson+TG789vn

**Comment by superhache** [comment]
thanks!!!!!

**Comment by m57** [comment]
This also helped me thanks ! :)
