### ISSUE TITLE
HUGE uncompressed size in binwalk output

### ISSUE THREAD

**Issue by shivang1989** [devttys0/binwalk#260]
I'm trying to run binwalk on a firmware but the command 'binwalk firmware.bin' outputs LZMA compressed data which has uncompressed size as 3468924096+ Gigabytes. 

> binwalk firmware.bin

` DECIMAL       HEXADECIMAL     DESCRIPTION`
` ----------------------------------------------------------------------`
`  384272        0x5DD10         Base64 standard index table`
`  428268        0x688EC         Base64 standard index table`
 ` 454224        0x6EE50         LZMA compressed data, properties: 0x6C, dictionary size: 33554432 bytes,   uncompressed size: 3468924096053250820 bytes`

Actual size of firmware.bin is 500KB

What is going wrong ? Am I missing something ?

**Comment by vido89** [comment]
Can you provide as a link to actual firmware ?

**Comment by itdaniher** [comment]
Dollars to donuts it's not actually LZMA... This sounds like a false positive, but too soon to say without firmware.bin...

**Comment by shivang1989** [comment]
Sorry for late reply :( 
Here is the firmware -- http://bit.ly/2pwaRTG

**Comment by devttys0** [comment]
To be honest, there doesn't seem to be anything in this firmware image to "binwalk". It looks like straight, uncompressed, unencrypted, code and data (tons of ASCII strings too). Given the size of the firmware, it's definitely not running Linux, and there is unlikely any form of file system in the firmware image. I don't know what the architecture is, but it sounds like you need a disassembler, not binwalk!

As for the LZMA issue, I suspect that you are using an older version of binwalk, or that you are running binwalk under Python2 and do not have the `python-lzma` module installed (this module is packaged with Python3 by default). If this module is available, binwalk uses it to validate possible LZMA compressions, and I do not see any valid LZMA results listed when running binwalk on the firmware image:

```
$ binwalk firmware.bin 

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
384272        0x5DD10         Base64 standard index table
428268        0x688EC         Base64 standard index table
```

**Comment by 0BuRner** [comment]
I guess you're the original author of this post (because it seems to be the same firmware) but someone replied with a so interesting and complete answer that I have to share it : https://reverseengineering.stackexchange.com/questions/15088/lzma-file-format-not-recognized-details-enclosed

**Comment by 0BuRner** [comment]
I guess you're the original author of this post (because it seems to be the same firmware) but someone replied with a so interesting and complete answer that I have to share it : https://reverseengineering.stackexchange.com/questions/15088/lzma-file-format-not-recognized-details-enclosed

**Comment by shivang1989** [comment]
Yes that question belongs to me. The answer there is interesting and now I am completely confused. 
I too feel strongly that its not a running linux. It's just 500KB *sighs*. 
The firmware's strings show paths like /application/something/something/<some-file.c>. 
What is this pointing to ? Where are all this directories ? 
Apologies for such silly questions but I have just started with firmware analysis.

**Comment by vido89** [comment]
@shivang1989 Those paths do not point to anything those are just comments

**Comment by shivang1989** [comment]
@vido89 Oh I see! I think I will have to dig deeper some other way because this bin file contains nothing of interest. 
I will update here (or that stackexchange thread) if I find anything interesting. 

Thank you guys for the pointers.
