### ISSUE TITLE
README.md and INSTALL.md appears conflicting on whether or not python-lzma is required

### ISSUE THREAD

**Issue by sundhaug92** [devttys0/binwalk#262]
Is python-lzma required or not?

README.md: python-lzma named specifically, optional dependencies listed in INSTALL.md

INSTALL.md: "Although all binwalk run-time dependencies are optional, the python-lzma module is highly recommended for improving the reliability of signature scans"

Suggestion:

a) Strongly recommend python-lzma
b) Require python-lzma
c) Describe python-lzma as a suggested/optional module

**Comment by devttys0** [comment]
It is technically optional, but strongly recommended. I've updated the wording in the README.md to be more explicit. Thanks!

**Comment by sundhaug92** [comment]
Thanks for the fix in 30efe97
