### ISSUE TITLE
Binwalk import error

### ISSUE THREAD

**Issue by suruchi1701** [devttys0/binwalk#298]
Hi I am facing below error when I am trying to import Binwalk 

> from binwalk import Binwalk
> ImportError: cannot import name Binwalk

**Comment by devttys0** [comment]
You'll want to do something like:

```
import binwalk

binwalk.scan(.....)
```

See the [Wiki](https://github.com/devttys0/binwalk/wiki/Scripting-With-the-Python-API) for an example of using binwalk in Python.
