### ISSUE TITLE
Update._do_update_from_svn failed (404)

### ISSUE THREAD

**Issue by probonopd** [devttys0/binwalk#94]
Binwalk v1.3.0 beta installed on the Mac with /usr/local/bin/brew install binwalk fails:
```
sudo binwalk -u

Update._do_update_from_svn failed to update file 
'https://raw.github.com/devttys0/binwalk/master/src/binwalk/magic/zlib': 
HTTP Error 404: Not Found
```

**Comment by devttys0** [comment]
The `-u` option is no longer supported, and current signatures are not compatible with v1.3.0. I'd suggest grabbing the latest code from the master branch, which should install fine on OSX.
