### ISSUE TITLE
Request: Provide API mechanism to return path of extracted result

### ISSUE THREAD

**Issue by ddcc** [devttys0/binwalk#97]
Currently, there doesn't seem to be an easy method to determine the path of an extracted result. Internally, the path is currently generated by os.path.join(unique_file_name('_' + os.path.basename(path), extension='extracted'), unique_file_name(bname, extension)), which changes depending on the presence of other similarly named files that may already exist on disk. Would it be possible to add an additional field to the results object returned by binwalk.scan() that has an e.g. "path" attribute?

**Comment by devttys0** [comment]
Each module returned by `binwalk.scan` has an `extractor` attribute. I've added a `directory` attribute to this, so you can retrieve the base extraction directory:

```
for module in binwalk.scan():
   print "Extraction base directory:", module.extractor.directory
```

`module.extractor.directory` will be set to `None` if no extraction directory was created.
